source "https://supermarket.getchef.com"

metadata

cookbook 'apt'
cookbook 'ark'
cookbook 'build-essential'
cookbook 'git'
cookbook 'imagemagick'
cookbook 'install_from'
cookbook 'ohai'
cookbook 'java'
cookbook 'openssl'
cookbook 'sudo'
cookbook 'redis'
cookbook 'logrotate'
cookbook 'mongodb'
cookbook 'runit'
cookbook 'rbenv', git: 'git://github.com/fnichol/chef-rbenv.git'
cookbook 'postgresql', "0.15.0", git: 'git://github.com/phlipper/chef-postgresql'
cookbook 'locale', git: 'git://github.com/hw-cookbooks/locale/'
cookbook 'mysql'
cookbook 'elasticsearch'
cookbook 'backup', git: 'git://github.com/damm/backup'
cookbook 'monit'
cookbook 'rabbitmq'