default[:deploy_user][:username] = 'ninja'
default[:deploy_user][:password] = 'ninja'
default[:deploy_user][:ruby_version] = '1.9.3-p448'
default[:deploy_user][:database_username] = 'ninja'
default[:deploy_user][:database_password] = 'ninja'
default[:deploy_user][:database_root_password] = 'ninja'
