default[:deploy_user][:username] = 'ninja'
default[:deploy_user][:password] = 'ninja'
default[:deploy_user][:ruby_version] = '1.9.3-p327'
default[:deploy_user][:db_username] = 'ninja'
default[:deploy_user][:db_password] = 'ninja'
default[:deploy_user][:db_root_password] = 'ninja'
